DROP DATABASE IF EXISTS feedback WITH (FORCE); 

CREATE DATABASE feedback;

\c feedback

-- createdb feedback

CREATE TABLE threads (
        id SERIAL NOT NULL,
        name VARCHAR(64) NOT NULL,
        PRIMARY KEY (id)
);

CREATE TABLE calls (
        id SERIAL NOT NULL,
        room_id VARCHAR(64) NOT NULL,
        author_id INTEGER,
        recipient_id INTEGER,
        lobby_timestamp TIMESTAMP WITHOUT TIME ZONE,
        start_timestamp TIMESTAMP WITHOUT TIME ZONE,
        end_timestamp TIMESTAMP WITHOUT TIME ZONE,
        in_call BOOLEAN,
        PRIMARY KEY (id)
);

CREATE TABLE countries (
        iso VARCHAR(2) NOT NULL,
        name VARCHAR(64) NOT NULL,
        PRIMARY KEY (iso)
);

CREATE TABLE languages (
        code VARCHAR(8) NOT NULL,
        name VARCHAR(64) NOT NULL,
        PRIMARY KEY (code)
);

CREATE TABLE users (
        id SERIAL NOT NULL,
        username VARCHAR(64) NOT NULL,
        password TEXT NOT NULL,
        email VARCHAR(320) NOT NULL,
        first_name VARCHAR(50) NOT NULL,
        last_name VARCHAR(50) NOT NULL,
        class_color TEXT NOT NULL,
        is_online BOOLEAN,
        city VARCHAR(50),
        country_iso VARCHAR(2) NOT NULL,
        target_language TEXT,
        PRIMARY KEY (id),
        UNIQUE (username),
        FOREIGN KEY(country_iso) REFERENCES countries (iso)
);

CREATE TABLE messages (
        id SERIAL NOT NULL,
        thread_id INTEGER,
        author_id INTEGER,
        recipient_id INTEGER,
        message_text VARCHAR(2048),
        message_language VARCHAR(64),
        translated_text VARCHAR(2048),
        translated_language VARCHAR(64),
        timestamp TIMESTAMP WITHOUT TIME ZONE,
        PRIMARY KEY (id),
        FOREIGN KEY(thread_id) REFERENCES threads (id)
);

CREATE TABLE contacts (
        user_id INTEGER NOT NULL,
        contact_id INTEGER NOT NULL,
        is_pending BOOLEAN,
        is_chatting BOOLEAN,
        is_calling BOOLEAN,
        PRIMARY KEY (user_id, contact_id),
        FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE cascade,
        FOREIGN KEY(contact_id) REFERENCES users (id) ON DELETE cascade
);

CREATE TABLE users_threads (
        user_id INTEGER NOT NULL,
        thread_id INTEGER NOT NULL,
        PRIMARY KEY (user_id, thread_id),
        FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE cascade,
        FOREIGN KEY(thread_id) REFERENCES threads (id) ON DELETE cascade
);

CREATE TABLE users_calls (
        user_id INTEGER NOT NULL,
        call_id INTEGER NOT NULL,
        PRIMARY KEY (user_id, call_id),
        FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE cascade,
        FOREIGN KEY(call_id) REFERENCES calls (id) ON DELETE cascade
);

CREATE TABLE users_languages (
        user_id INTEGER NOT NULL,
        language_code VARCHAR(8) NOT NULL,
        PRIMARY KEY (user_id, language_code),
        FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE cascade,
        FOREIGN KEY(language_code) REFERENCES languages (code) ON DELETE cascade
);


INSERT INTO countries (iso, name) 
VALUES ('AF', 'Afghanistan'),
('AX', 'Aland Islands'),
('AL', 'Albania'),
('DZ', 'Algeria'),
('AS', 'American Samoa'),
('AD', 'Andorra'),
('AO', 'Angola'),
('AI', 'Anguilla'),
('AQ', 'Antarctica'),
('AG', 'Antigua and Barbuda'),
('AR', 'Argentina'),
('AM', 'Armenia'),
('AW', 'Aruba'),
('AU', 'Australia'),
('AT', 'Austria'),
('AZ', 'Azerbaijan'),
('BS', 'Bahamas'),
('BH', 'Bahrain'),
('BD', 'Bangladesh'),
('BB', 'Barbados'),
('BY', 'Belarus'),
('BE', 'Belgium'),
('BZ', 'Belize'),
('BJ', 'Benin'),
('BM', 'Bermuda'),
('BT', 'Bhutan'),
('BO', 'Bolivia'),
('BQ', 'Bonaire, Sint Eustatius and Saba'),
('BA', 'Bosnia and Herzegovina'),
('BW', 'Botswana'),
('BV', 'Bouvet Island'),
('BR', 'Brazil'),
('IO', 'British Indian Ocean Territory'),
('BN', 'Brunei Darussalam'),
('BG', 'Bulgaria'),
('BF', 'Burkina Faso'),
('BI', 'Burundi'),
('KH', 'Cambodia'),
('CM', 'Cameroon'),
('CA', 'Canada'),
('CV', 'Cape Verde'),
('KY', 'Cayman Islands'),
('CF', 'Central African Republic'),
('TD', 'Chad'),
('CL', 'Chile'),
('CN', 'China'),
('CX', 'Christmas Island'),
('CC', 'Cocos (Keeling) Islands'),
('CO', 'Colombia'),
('KM', 'Comoros'),
('CG', 'Congo'),
('CD', 'Congo, Democratic Republic of the Congo'),
('CK', 'Cook Islands'),
('CR', 'Costa Rica'),
('CI', 'Cote D''Ivoire'),
('HR', 'Croatia'),
('CU', 'Cuba'),
('CW', 'Curacao'),
('CY', 'Cyprus'),
('CZ', 'Czech Republic'),
('DK', 'Denmark'),
('DJ', 'Djibouti'),
('DM', 'Dominica'),
('DO', 'Dominican Republic'),
('EC', 'Ecuador'),
('EG', 'Egypt'),
('SV', 'El Salvador'),
('GQ', 'Equatorial Guinea'),
('ER', 'Eritrea'),
('EE', 'Estonia'),
('ET', 'Ethiopia'),
('FK', 'Falkland Islands (Malvinas)'),
('FO', 'Faroe Islands'),
('FJ', 'Fiji'),
('FI', 'Finland'),
('FR', 'France'),
('GF', 'French Guiana'),
('PF', 'French Polynesia'),
('TF', 'French Southern Territories'),
('GA', 'Gabon'),
('GM', 'Gambia'),
('GE', 'Georgia'),
('DE', 'Germany'),
('GH', 'Ghana'),
('GI', 'Gibraltar'),
('GR', 'Greece'),
('GL', 'Greenland'),
('GD', 'Grenada'),
('GP', 'Guadeloupe'),
('GU', 'Guam'),
('GT', 'Guatemala'),
('GG', 'Guernsey'),
('GN', 'Guinea'),
('GW', 'Guinea-Bissau'),
('GY', 'Guyana'),
('HT', 'Haiti'),
('HM', 'Heard Island and Mcdonald Islands'),
('VA', 'Holy See (Vatican City State)'),
('HN', 'Honduras'),
('HK', 'Hong Kong'),
('HU', 'Hungary'),
('IS', 'Iceland'),
('IN', 'India'),
('ID', 'Indonesia'),
('IR', 'Iran, Islamic Republic of'),
('IQ', 'Iraq'),
('IE', 'Ireland'),
('IM', 'Isle of Man'),
('IL', 'Israel'),
('IT', 'Italy'),
('JM', 'Jamaica'),
('JP', 'Japan'),
('JE', 'Jersey'),
('JO', 'Jordan'),
('KZ', 'Kazakhstan'),
('KE', 'Kenya'),
('KI', 'Kiribati'),
('KP', 'Korea, Democratic People''s Republic of'),
('KR', 'Korea, Republic of'),
('XK', 'Kosovo'),
('KW', 'Kuwait'),
('KG', 'Kyrgyzstan'),
('LA', 'Lao People''s Democratic Republic'),
('LV', 'Latvia'),
('LB', 'Lebanon'),
('LS', 'Lesotho'),
('LR', 'Liberia'),
('LY', 'Libyan Arab Jamahiriya'),
('LI', 'Liechtenstein'),
('LT', 'Lithuania'),
('LU', 'Luxembourg'),
('MO', 'Macao'),
('MK', 'Macedonia, the Former Yugoslav Republic of'),
('MG', 'Madagascar'),
('MW', 'Malawi'),
('MY', 'Malaysia'),
('MV', 'Maldives'),
('ML', 'Mali'),
('MT', 'Malta'),
('MH', 'Marshall Islands'),
('MQ', 'Martinique'),
('MR', 'Mauritania'),
('MU', 'Mauritius'),
('YT', 'Mayotte'),
('MX', 'Mexico'),
('FM', 'Micronesia, Federated States of'),
('MD', 'Moldova, Republic of'),
('MC', 'Monaco'),
('MN', 'Mongolia'),
('ME', 'Montenegro'),
('MS', 'Montserrat'),
('MA', 'Morocco'),
('MZ', 'Mozambique'),
('MM', 'Myanmar'),
('NA', 'Namibia'),
('NR', 'Nauru'),
('NP', 'Nepal'),
('NL', 'Netherlands'),
('AN', 'Netherlands Antilles'),
('NC', 'New Caledonia'),
('NZ', 'New Zealand'),
('NI', 'Nicaragua'),
('NE', 'Niger'),
('NG', 'Nigeria'),
('NU', 'Niue'),
('NF', 'Norfolk Island'),
('MP', 'Northern Mariana Islands'),
('NO', 'Norway'),
('OM', 'Oman'),
('PK', 'Pakistan'),
('PW', 'Palau'),
('PS', 'Palestinian Territory, Occupied'),
('PA', 'Panama'),
('PG', 'Papua New Guinea'),
('PY', 'Paraguay'),
('PE', 'Peru'),
('PH', 'Philippines'),
('PN', 'Pitcairn'),
('PL', 'Poland'),
('PT', 'Portugal'),
('PR', 'Puerto Rico'),
('QA', 'Qatar'),
('RE', 'Reunion'),
('RO', 'Romania'),
('RU', 'Russian Federation'),
('RW', 'Rwanda'),
('BL', 'Saint Barthelemy'),
('SH', 'Saint Helena'),
('KN', 'Saint Kitts and Nevis'),
('LC', 'Saint Lucia'),
('MF', 'Saint Martin'),
('PM', 'Saint Pierre and Miquelon'),
('VC', 'Saint Vincent and the Grenadines'),
('WS', 'Samoa'),
('SM', 'San Marino'),
('ST', 'Sao Tome and Principe'),
('SA', 'Saudi Arabia'),
('SN', 'Senegal'),
('RS', 'Serbia'),
('CS', 'Serbia and Montenegro'),
('SC', 'Seychelles'),
('SL', 'Sierra Leone'),
('SG', 'Singapore'),
('SX', 'Sint Maarten'),
('SK', 'Slovakia'),
('SI', 'Slovenia'),
('SB', 'Solomon Islands'),
('SO', 'Somalia'),
('ZA', 'South Africa'),
('GS', 'South Georgia and the South Sandwich Islands'),
('SS', 'South Sudan'),
('ES', 'Spain'),
('LK', 'Sri Lanka'),
('SD', 'Sudan'),
('SR', 'Suriname'),
('SJ', 'Svalbard and Jan Mayen'),
('SZ', 'Swaziland'),
('SE', 'Sweden'),
('CH', 'Switzerland'),
('SY', 'Syrian Arab Republic'),
('TW', 'Taiwan, Province of China'),
('TJ', 'Tajikistan'),
('TZ', 'Tanzania, United Republic of'),
('TH', 'Thailand'),
('TL', 'Timor-Leste'),
('TG', 'Togo'),
('TK', 'Tokelau'),
('TO', 'Tonga'),
('TT', 'Trinidad and Tobago'),
('TN', 'Tunisia'),
('TR', 'Turkey'),
('TM', 'Turkmenistan'),
('TC', 'Turks and Caicos Islands'),
('TV', 'Tuvalu'),
('UG', 'Uganda'),
('UA', 'Ukraine'),
('AE', 'United Arab Emirates'),
('GB', 'United Kingdom'),
('US', 'United States'),
('UM', 'United States Minor Outlying Islands'),
('UY', 'Uruguay'),
('UZ', 'Uzbekistan'),
('VU', 'Vanuatu'),
('VE', 'Venezuela'),
('VN', 'Viet Nam'),
('VG', 'Virgin Islands, British'),
('VI', 'Virgin Islands, U.s.'),
('WF', 'Wallis and Futuna'),
('EH', 'Western Sahara'),
('YE', 'Yemen'),
('ZM', 'Zambia'),
('ZW', 'Zimbabwe');


INSERT INTO languages (code, name) 
VALUES ('af', 'Afrikaans'),
('sq', 'Albanian'),
('am', 'Amharic'),
('ar', 'Arabic'),
('hy', 'Armenian'),
('as', 'Assamese'),
('ay', 'Aymara'),
('az', 'Azerbaijani'),
('bm', 'Bambara'),
('eu', 'Basque'),
('be', 'Belarusian'),
('bn', 'Bengali'),
('bho', 'Bhojpuri'),
('bs', 'Bosnian'),
('bg', 'Bulgarian'),
('ca', 'Catalan'),
('ceb', 'Cebuano'),
('zh', 'Chinese (Simplified)'),
('zh-TW', 'Chinese (Traditional)'),
('co', 'Corsican'),
('hr', 'Croatian'),
('cs', 'Czech'),
('da', 'Danish'),
('dv', 'Dhivehi'),
('doi', 'Dogri'),
('nl', 'Dutch'),
('en', 'English'),
('eo', 'Esperanto'),
('et', 'Estonian'),
('ee', 'Ewe'),
('fil', 'Filipino (Tagalog)'),
('fi', 'Finnish'),
('fr', 'French'),
('fy', 'Frisian'),
('gl', 'Galician'),
('ka', 'Georgian'),
('de', 'German'),
('el', 'Greek'),
('gn', 'Guarani'),
('gu', 'Gujarati'),
('ht', 'Haitian Creole'),
('ha', 'Hausa'),
('haw', 'Hawaiian'),
('he', 'Hebrew'),
('iw', 'Hebrew'),
('hi', 'Hindi'),
('hmn', 'Hmong'),
('hu', 'Hungarian'),
('is', 'Icelandic'),
('ig', 'Igbo'),
('ilo', 'Ilocano'),
('id', 'Indonesian'),
('ga', 'Irish'),
('it', 'Italian'),
('ja', 'Japanese'),
('jv', 'Javanese'),
('kn', 'Kannada'),
('kk', 'Kazakh'),
('km', 'Khmer'),
('rw', 'Kinyarwanda'),
('gom', 'Konkani'),
('ko', 'Korean'),
('kri', 'Krio'),
('ku', 'Kurdish'),
('ckb', 'Kurdish (Sorani)'),
('ky', 'Kyrgyz'),
('lo', 'Lao'),
('la', 'Latin'),
('lv', 'Latvian'),
('ln', 'Lingala'),
('lt', 'Lithuanian'),
('lg', 'Luganda'),
('lb', 'Luxembourgish'),
('mk', 'Macedonian'),
('mai', 'Maithili'),
('mg', 'Malagasy'),
('ms', 'Malay'),
('ml', 'Malayalam'),
('mt', 'Maltese'),
('mi', 'Maori'),
('mr', 'Marathi'),
('mni-Mtei', 'Meiteilon (Manipuri)'),
('lus', 'Mizo'),
('mn', 'Mongolian'),
('my', 'Myanmar (Burmese)'),
('ne', 'Nepali'),
('no', 'Norwegian'),
('ny', 'Nyanja (Chichewa)'),
('or', 'Odia (Oriya)'),
('om', 'Oromo'),
('ps', 'Pashto'),
('fa', 'Persian'),
('pl', 'Polish'),
('pt', 'Portuguese (Portugal, Brazil)'),
('pa', 'Punjabi'),
('qu', 'Quechua'),
('ro', 'Romanian'),
('ru', 'Russian'),
('sm', 'Samoan'),
('sa', 'Sanskrit'),
('gd', 'Scots Gaelic'),
('nso', 'Sepedi'),
('sr', 'Serbian'),
('st', 'Sesotho'),
('sn', 'Shona'),
('sd', 'Sindhi'),
('si', 'Sinhala (Sinhalese)'),
('sk', 'Slovak'),
('sl', 'Slovenian'),
('so', 'Somali'),
('es', 'Spanish'),
('su', 'Sundanese'),
('sw', 'Swahili'),
('sv', 'Swedish'),
('tl', 'Tagalog (Filipino)'),
('tg', 'Tajik'),
('ta', 'Tamil'),
('tt', 'Tatar'),
('te', 'Telugu'),
('th', 'Thai'),
('ti', 'Tigrinya'),
('ts', 'Tsonga'),
('tr', 'Turkish'),
('tk', 'Turkmen'),
('ak', 'Twi (Akan)'),
('uk', 'Ukrainian'),
('ur', 'Urdu'),
('ug', 'Uyghur'),
('uz', 'Uzbek'),
('vi', 'Vietnamese'),
('cy', 'Welsh'),
('xh', 'Xhosa'),
('yi', 'Yiddish'),
('yo', 'Yoruba'),
('zu', 'Zulu');

-- INSERT INTO languages (code, name) 
-- VALUES ('AF','Afrikanns'),
-- ('SQ','Albanian'),
-- ('AR','Arabic'),
-- ('HY','Armenian'),
-- ('EU','Basque'),
-- ('BN','Bengali'),
-- ('BG','Bulgarian'),
-- ('CA','Catalan'),
-- ('KM','Cambodian'),
-- ('ZH', 'Chinese (Mandarin)'),
-- ('HR', 'Croation'),
-- ('CS', 'Czech'),
-- ('DA', 'Danish'),
-- ('NL', 'Dutch'),
-- ('EN', 'English'),
-- ('ET', 'Estonian'),
-- ('FJ', 'Fiji'),
-- ('FI', 'Finnish'),
-- ('FR', 'French'),
-- ('KA', 'Georgian'),
-- ('DE', 'German'),
-- ('EL', 'Greek'),
-- ('GU', 'Gujarati'),
-- ('HE', 'Hebrew'),
-- ('HI', 'Hindi'),
-- ('HU', 'Hungarian'),
-- ('IS', 'Icelandic'),
-- ('ID', 'Indonesian'),
-- ('GA', 'Irish'),
-- ('IT', 'Italian'),
-- ('JA', 'Japanese'),
-- ('JW', 'Javanese'),
-- ('KO', 'Korean'),
-- ('LA', 'Latin'),
-- ('LV', 'Latvian'),
-- ('LT', 'Lithuanian'),
-- ('MK', 'Macedonian'),
-- ('MS', 'Malay'),
-- ('ML', 'Malayalam'),
-- ('MT', 'Maltese'),
-- ('MI', 'Maori'),
-- ('MR', 'Marathi'),
-- ('MN', 'Mongolian'),
-- ('NE', 'Nepali'),
-- ('NO', 'Norwegian'),
-- ('FA', 'Persian'),
-- ('PL', 'Polish'),
-- ('PT', 'Portuguese'),
-- ('PA', 'Punjabi'),
-- ('QU', 'Quechua'),
-- ('RO', 'Romanian'),
-- ('RU', 'Russian'),
-- ('SM', 'Samoan'),
-- ('SR', 'Serbian'),
-- ('SK', 'Slovak'),
-- ('SL', 'Slovenian'),
-- ('ES', 'Spanish'),
-- ('SW', 'Swahili'),
-- ('SV', 'Swedish'),
-- ('TA', 'Tamil'),
-- ('TT', 'Tatar'),
-- ('TE', 'Telugu'),
-- ('TH', 'Thai'),
-- ('BO', 'Tibetan'),
-- ('TO', 'Tonga'),
-- ('TR', 'Turkish'),
-- ('UK', 'Ukranian'),
-- ('UR', 'Urdu'),
-- ('UZ', 'Uzbek'),
-- ('VI', 'Vietnamese'),
-- ('CY', 'Welsh'),
-- ('XH', 'Xhosa');