from models import db, User, Message, Thread, UserThread, Contact, Country, Language
from run import app

db.drop_all()
db.create_all()

User.query.delete()
Message.query.delete()
Thread.query.delete()
UserThread.query.delete()
Contact.query.delete()
Country.query.delete()
Language.query.delete()

# c1 = Country(iso='AF', name='Afghanistan')
# c2 = Country(iso='AX', name='Aland Islands')
# c3 = Country(iso='AL', name='Albania')
# c4 = Country(iso='DZ', name='Algeria')
# c5 = Country(iso='AS', name='American Samoa')
# c6 = Country(iso='AD', name='Andorra')
# c7 = Country(iso='AO', name='Angola')
# c8 = Country(iso='AI', name='Anguilla')
# c9 = Country(iso='AQ', name='Antarctica')
# c10 = Country(iso='AG', name='Antigua and Barbuda')
# c11 = Country(iso='AR', name='Argentina')
# c12 = Country(iso='AM', name='Armenia')
# c13 = Country(iso='AW', name='Aruba')
# c14 = Country(iso='AU', name='Australia')
# c15 = Country(iso='AT', name='Austria')
# c16 = Country(iso='AZ', name='Azerbaijan')
# c17 = Country(iso='BS', name='Bahamas')
# c18 = Country(iso='BH', name='Bahrain')
# c19 = Country(iso='BD', name='Bangladesh')
# c20 = Country(iso='BB', name='Barbados')
# c21 = Country(iso='BY', name='Belarus')
# c22 = Country(iso='BE', name='Belgium')
# c23 = Country(iso='BZ', name='Belize')
# c24 = Country(iso='BJ', name='Benin')
# c25 = Country(iso='BM', name='Bermuda')
# c26 = Country(iso='BT', name='Bhutan')
# c27 = Country(iso='BO', name='Bolivia')
# c28 = Country(iso='BQ', name='Bonaire, Sint Eustatius and Saba')
# c29 = Country(iso='BA', name='Bosnia and Herzegovina')
# c30 = Country(iso='BW', name='Botswana')
# c31 = Country(iso='BV', name='Bouvet Island')
# c32 = Country(iso='BR', name='Brazil')
# c33 = Country(iso='IO', name='British Indian Ocean Territory')
# c34 = Country(iso='BN', name='Brunei Darussalam')
# c35 = Country(iso='BG', name='Bulgaria')
# c36 = Country(iso='BF', name='Burkina Faso')
# c37 = Country(iso='BI', name='Burundi')
# c38 = Country(iso='KH', name='Cambodia')
# c39 = Country(iso='CM', name='Cameroon')
# c40 = Country(iso='CA', name='Canada')
# c41 = Country(iso='CV', name='Cape Verde')
# c42 = Country(iso='KY', name='Cayman Islands')
# c43 = Country(iso='CF', name='Central African Republic')
# c44 = Country(iso='TD', name='Chad')
# c45 = Country(iso='CL', name='Chile')
# c46 = Country(iso='CN', name='China')
# c47 = Country(iso='CX', name='Christmas Island')
# c48 = Country(iso='CC', name='Cocos (Keeling) Islands')
# c49 = Country(iso='CO', name='Colombia')
# c50 = Country(iso='KM', name='Comoros')
# c51 = Country(iso='CG', name='Congo')
# c52 = Country(iso='CD', name='Congo, Democratic Republic of the Congo')
# c53 = Country(iso='CK', name='Cook Islands')
# c54 = Country(iso='CR', name='Costa Rica')
# c55 = Country(iso='CI', name='Cote D''Ivoire')
# c56 = Country(iso='HR', name='Croatia')
# c57 = Country(iso='CU', name='Cuba')
# c58 = Country(iso='CW', name='Curacao')
# c59 = Country(iso='CY', name='Cyprus')
# c60 = Country(iso='CZ', name='Czech Republic')
# c61 = Country(iso='DK', name='Denmark')
# c62 = Country(iso='DJ', name='Djibouti')
# c63 = Country(iso='DM', name='Dominica')
# c64 = Country(iso='DO', name='Dominican Republic')
# c65 = Country(iso='EC', name='Ecuador')
# c66 = Country(iso='EG', name='Egypt')
# c67 = Country(iso='SV', name='El Salvador')
# c68 = Country(iso='GQ', name='Equatorial Guinea')
# c69 = Country(iso='ER', name='Eritrea')
# c70 = Country(iso='EE', name='Estonia')
# c71 = Country(iso='ET', name='Ethiopia')
# c72 = Country(iso='FK', name='Falkland Islands (Malvinas)')
# c73 = Country(iso='FO', name='Faroe Islands')
# c74 = Country(iso='FJ', name='Fiji')
# c75 = Country(iso='FI', name='Finland')
# c76 = Country(iso='FR', name='France')
# c77 = Country(iso='GF', name='French Guiana')
# c78 = Country(iso='PF', name='French Polynesia')
# c79 = Country(iso='TF', name='French Southern Territories')
# c80 = Country(iso='GA', name='Gabon')
# c81 = Country(iso='GM', name='Gambia')
# c82 = Country(iso='GE', name='Georgia')
# c83 = Country(iso='DE', name='Germany')
# c84 = Country(iso='GH', name='Ghana')
# c85 = Country(iso='GI', name='Gibraltar')
# c86 = Country(iso='GR', name='Greece')
# c87 = Country(iso='GL', name='Greenland')
# c88 = Country(iso='GD', name='Grenada')
# c89 = Country(iso='GP', name='Guadeloupe')
# c90 = Country(iso='GU', name='Guam')
# c91 = Country(iso='GT', name='Guatemala')
# c92 = Country(iso='GG', name='Guernsey')
# c93 = Country(iso='GN', name='Guinea')
# c94 = Country(iso='GW', name='Guinea-Bissau')
# c95 = Country(iso='GY', name='Guyana')
# c96 = Country(iso='HT', name='Haiti')
# c97 = Country(iso='HM', name='Heard Island and Mcdonald Islands')
# c98 = Country(iso='VA', name='Holy See (Vatican City State)')
# c99 = Country(iso='HN', name='Honduras')
# c100 = Country(iso='HK', name='Hong Kong')
# c101 = Country(iso='HU', name='Hungary')
# c102 = Country(iso='IS', name='Iceland')
# c103 = Country(iso='IN', name='India')
# c104 = Country(iso='ID', name='Indonesia')
# c105 = Country(iso='IR', name='Iran, Islamic Republic of')
# c106 = Country(iso='IQ', name='Iraq')
# c107 = Country(iso='IE', name='Ireland')
# c108 = Country(iso='IM', name='Isle of Man')
# c109 = Country(iso='IL', name='Israel')
# c110 = Country(iso='IT', name='Italy')
# c111 = Country(iso='JM', name='Jamaica')
# c112 = Country(iso='JP', name='Japan')
# c113 = Country(iso='JE', name='Jersey')
# c114 = Country(iso='JO', name='Jordan')
# c115 = Country(iso='KZ', name='Kazakhstan')
# c116 = Country(iso='KE', name='Kenya')
# c117 = Country(iso='KI', name='Kiribati')
# c118 = Country(iso='KP', name='Korea, Democratic People''s Republic of')
# c119 = Country(iso='KR', name='Korea, Republic of')
# c120 = Country(iso='XK', name='Kosovo')
# c121 = Country(iso='KW', name='Kuwait')
# c122 = Country(iso='KG', name='Kyrgyzstan')
# c123 = Country(iso='LA', name='Lao People''s Democratic Republic')
# c124 = Country(iso='LV', name='Latvia')
# c125 = Country(iso='LB', name='Lebanon')
# c126 = Country(iso='LS', name='Lesotho')
# c127 = Country(iso='LR', name='Liberia')
# c128 = Country(iso='LY', name='Libyan Arab Jamahiriya')
# c129 = Country(iso='LI', name='Liechtenstein')
# c130 = Country(iso='LT', name='Lithuania')
# c131 = Country(iso='LU', name='Luxembourg')
# c132 = Country(iso='MO', name='Macao')
# c133 = Country(iso='MK', name='Macedonia, the Former Yugoslav Republic of')
# c134 = Country(iso='MG', name='Madagascar')
# c135 = Country(iso='MW', name='Malawi')
# c136 = Country(iso='MY', name='Malaysia')
# c137 = Country(iso='MV', name='Maldives')
# c138 = Country(iso='ML', name='Mali')
# c139 = Country(iso='MT', name='Malta')
# c140 = Country(iso='MH', name='Marshall Islands')
# c141 = Country(iso='MQ', name='Martinique')
# c142 = Country(iso='MR', name='Mauritania')
# c143 = Country(iso='MU', name='Mauritius')
# c144 = Country(iso='YT', name='Mayotte')
# c145 = Country(iso='MX', name='Mexico')
# c146 = Country(iso='FM', name='Micronesia, Federated States of')
# c147 = Country(iso='MD', name='Moldova, Republic of')
# c148 = Country(iso='MC', name='Monaco')
# c149 = Country(iso='MN', name='Mongolia')
# c150 = Country(iso='ME', name='Montenegro')
# c151 = Country(iso='MS', name='Montserrat')
# c152 = Country(iso='MA', name='Morocco')
# c153 = Country(iso='MZ', name='Mozambique')
# c154 = Country(iso='MM', name='Myanmar')
# c155 = Country(iso='NA', name='Namibia')
# c156 = Country(iso='NR', name='Nauru')
# c157 = Country(iso='NP', name='Nepal')
# c158 = Country(iso='NL', name='Netherlands')
# c159 = Country(iso='AN', name='Netherlands Antilles')
# c160 = Country(iso='NC', name='New Caledonia')
# c161 = Country(iso='NZ', name='New Zealand')
# c162 = Country(iso='NI', name='Nicaragua')
# c163 = Country(iso='NE', name='Niger')
# c164 = Country(iso='NG', name='Nigeria')
# c165 = Country(iso='NU', name='Niue')
# c166 = Country(iso='NF', name='Norfolk Island')
# c167 = Country(iso='MP', name='Northern Mariana Islands')
# c168 = Country(iso='NO', name='Norway')
# c169 = Country(iso='OM', name='Oman')
# c170 = Country(iso='PK', name='Pakistan')
# c171 = Country(iso='PW', name='Palau')
# c172 = Country(iso='PS', name='Palestinian Territory, Occupied')
# c173 = Country(iso='PA', name='Panama')
# c174 = Country(iso='PG', name='Papua New Guinea')
# c175 = Country(iso='PY', name='Paraguay')
# c176 = Country(iso='PE', name='Peru')
# c177 = Country(iso='PH', name='Philippines')
# c178 = Country(iso='PN', name='Pitcairn')
# c179 = Country(iso='PL', name='Poland')
# c180 = Country(iso='PT', name='Portugal')
# c181 = Country(iso='PR', name='Puerto Rico')
# c182 = Country(iso='QA', name='Qatar')
# c183 = Country(iso='RE', name='Reunion')
# c184 = Country(iso='RO', name='Romania')
# c185 = Country(iso='RU', name='Russian Federation')
# c186 = Country(iso='RW', name='Rwanda')
# c187 = Country(iso='BL', name='Saint Barthelemy')
# c188 = Country(iso='SH', name='Saint Helena')
# c189 = Country(iso='KN', name='Saint Kitts and Nevis')
# c190 = Country(iso='LC', name='Saint Lucia')
# c191 = Country(iso='MF', name='Saint Martin')
# c192 = Country(iso='PM', name='Saint Pierre and Miquelon')
# c193 = Country(iso='VC', name='Saint Vincent and the Grenadines')
# c194 = Country(iso='WS', name='Samoa')
# c195 = Country(iso='SM', name='San Marino')
# c196 = Country(iso='ST', name='Sao Tome and Principe')
# c197 = Country(iso='SA', name='Saudi Arabia')
# c198 = Country(iso='SN', name='Senegal')
# c199 = Country(iso='RS', name='Serbia')
# c200 = Country(iso='CS', name='Serbia and Montenegro')
# c201 = Country(iso='SC', name='Seychelles')
# c202 = Country(iso='SL', name='Sierra Leone')
# c203 = Country(iso='SG', name='Singapore')
# c204 = Country(iso='SX', name='Sint Maarten')
# c205 = Country(iso='SK', name='Slovakia')
# c206 = Country(iso='SI', name='Slovenia')
# c207 = Country(iso='SB', name='Solomon Islands')
# c208 = Country(iso='SO', name='Somalia')
# c209 = Country(iso='ZA', name='South Africa')
# c210 = Country(iso='GS', name='South Georgia and the South Sandwich Islands')
# c211 = Country(iso='SS', name='South Sudan')
# c212 = Country(iso='ES', name='Spain')
# c213 = Country(iso='LK', name='Sri Lanka')
# c214 = Country(iso='SD', name='Sudan')
# c215 = Country(iso='SR', name='Suriname')
# c216 = Country(iso='SJ', name='Svalbard and Jan Mayen')
# c217 = Country(iso='SZ', name='Swaziland')
# c218 = Country(iso='SE', name='Sweden')
# c219 = Country(iso='CH', name='Switzerland')
# c220 = Country(iso='SY', name='Syrian Arab Republic')
# c221 = Country(iso='TW', name='Taiwan, Province of China')
# c222 = Country(iso='TJ', name='Tajikistan')
# c223 = Country(iso='TZ', name='Tanzania, United Republic of')
# c224 = Country(iso='TH', name='Thailand')
# c225 = Country(iso='TL', name='Timor-Leste')
# c226 = Country(iso='TG', name='Togo')
# c227 = Country(iso='TK', name='Tokelau')
# c228 = Country(iso='TO', name='Tonga')
# c229 = Country(iso='TT', name='Trinidad and Tobago')
# c230 = Country(iso='TN', name='Tunisia')
# c231 = Country(iso='TR', name='Turkey')
# c232 = Country(iso='TM', name='Turkmenistan')
# c233 = Country(iso='TC', name='Turks and Caicos Islands')
# c234 = Country(iso='TV', name='Tuvalu')
# c235 = Country(iso='UG', name='Uganda')
# c236 = Country(iso='UA', name='Ukraine')
# c237 = Country(iso='AE', name='United Arab Emirates')
# c238 = Country(iso='GB', name='United Kingdom')
# c239 = Country(iso='US', name='United States')
# c240 = Country(iso='UM', name='United States Minor Outlying Islands')
# c241 = Country(iso='UY', name='Uruguay')
# c242 = Country(iso='UZ', name='Uzbekistan')
# c243 = Country(iso='VU', name='Vanuatu')
# c244 = Country(iso='VE', name='Venezuela')
# c245 = Country(iso='VN', name='Viet Nam')
# c246 = Country(iso='VG', name='Virgin Islands, British')
# c247 = Country(iso='VI', name='Virgin Islands, U.s.')
# c248 = Country(iso='WF', name='Wallis and Futuna')
# c249 = Country(iso='EH', name='Western Sahara')
# c250 = Country(iso='YE', name='Yemen')
# c251 = Country(iso='ZM', name='Zambia')
# c252 = Country(iso='ZW', name='Zimbabwe')

# db.session.add(c1)
# db.session.add(c2)
# db.session.add(c3)
# db.session.add(c4)
# db.session.add(c5)
# db.session.add(c6)
# db.session.add(c7)
# db.session.add(c8)
# db.session.add(c9)
# db.session.add(c10)
# db.session.add(c11)
# db.session.add(c12)
# db.session.add(c13)
# db.session.add(c14)
# db.session.add(c15)
# db.session.add(c16)
# db.session.add(c17)
# db.session.add(c18)
# db.session.add(c19)
# db.session.add(c20)
# db.session.add(c21)
# db.session.add(c22)
# db.session.add(c23)
# db.session.add(c24)
# db.session.add(c25)
# db.session.add(c26)
# db.session.add(c27)
# db.session.add(c28)
# db.session.add(c29)
# db.session.add(c30)
# db.session.add(c31)
# db.session.add(c32)
# db.session.add(c33)
# db.session.add(c34)
# db.session.add(c35)
# db.session.add(c36)
# db.session.add(c37)
# db.session.add(c38)
# db.session.add(c39)
# db.session.add(c40)
# db.session.add(c41)
# db.session.add(c42)
# db.session.add(c43)
# db.session.add(c44)
# db.session.add(c45)
# db.session.add(c46)
# db.session.add(c47)
# db.session.add(c48)
# db.session.add(c49)
# db.session.add(c50)
# db.session.add(c51)
# db.session.add(c52)
# db.session.add(c53)
# db.session.add(c54)
# db.session.add(c55)
# db.session.add(c56)
# db.session.add(c57)
# db.session.add(c58)
# db.session.add(c59)
# db.session.add(c60)
# db.session.add(c61)
# db.session.add(c62)
# db.session.add(c63)
# db.session.add(c64)
# db.session.add(c65)
# db.session.add(c66)
# db.session.add(c67)
# db.session.add(c68)
# db.session.add(c69)
# db.session.add(c70)
# db.session.add(c71)
# db.session.add(c72)
# db.session.add(c73)
# db.session.add(c74)
# db.session.add(c75)
# db.session.add(c76)
# db.session.add(c77)
# db.session.add(c78)
# db.session.add(c79)
# db.session.add(c80)
# db.session.add(c81)
# db.session.add(c82)
# db.session.add(c83)
# db.session.add(c84)
# db.session.add(c85)
# db.session.add(c86)
# db.session.add(c87)
# db.session.add(c88)
# db.session.add(c89)
# db.session.add(c90)
# db.session.add(c91)
# db.session.add(c92)
# db.session.add(c93)
# db.session.add(c94)
# db.session.add(c95)
# db.session.add(c96)
# db.session.add(c97)
# db.session.add(c98)
# db.session.add(c99)
# db.session.add(c100)
# db.session.add(c101)
# db.session.add(c102)
# db.session.add(c103)
# db.session.add(c104)
# db.session.add(c105)
# db.session.add(c106)
# db.session.add(c107)
# db.session.add(c108)
# db.session.add(c109)
# db.session.add(c110)
# db.session.add(c111)
# db.session.add(c112)
# db.session.add(c113)
# db.session.add(c114)
# db.session.add(c115)
# db.session.add(c116)
# db.session.add(c117)
# db.session.add(c118)
# db.session.add(c119)
# db.session.add(c120)
# db.session.add(c121)
# db.session.add(c122)
# db.session.add(c123)
# db.session.add(c124)
# db.session.add(c125)
# db.session.add(c126)
# db.session.add(c127)
# db.session.add(c128)
# db.session.add(c129)
# db.session.add(c130)
# db.session.add(c131)
# db.session.add(c132)
# db.session.add(c133)
# db.session.add(c134)
# db.session.add(c135)
# db.session.add(c136)
# db.session.add(c137)
# db.session.add(c138)
# db.session.add(c139)
# db.session.add(c140)
# db.session.add(c141)
# db.session.add(c142)
# db.session.add(c143)
# db.session.add(c144)
# db.session.add(c145)
# db.session.add(c146)
# db.session.add(c147)
# db.session.add(c148)
# db.session.add(c149)
# db.session.add(c150)
# db.session.add(c151)
# db.session.add(c152)
# db.session.add(c153)
# db.session.add(c154)
# db.session.add(c155)
# db.session.add(c156)
# db.session.add(c157)
# db.session.add(c158)
# db.session.add(c159)
# db.session.add(c160)
# db.session.add(c161)
# db.session.add(c162)
# db.session.add(c163)
# db.session.add(c164)
# db.session.add(c165)
# db.session.add(c166)
# db.session.add(c167)
# db.session.add(c168)
# db.session.add(c169)
# db.session.add(c170)
# db.session.add(c171)
# db.session.add(c172)
# db.session.add(c173)
# db.session.add(c174)
# db.session.add(c175)
# db.session.add(c176)
# db.session.add(c177)
# db.session.add(c178)
# db.session.add(c179)
# db.session.add(c180)
# db.session.add(c181)
# db.session.add(c182)
# db.session.add(c183)
# db.session.add(c184)
# db.session.add(c185)
# db.session.add(c186)
# db.session.add(c187)
# db.session.add(c188)
# db.session.add(c189)
# db.session.add(c190)
# db.session.add(c191)
# db.session.add(c192)
# db.session.add(c193)
# db.session.add(c194)
# db.session.add(c195)
# db.session.add(c196)
# db.session.add(c197)
# db.session.add(c198)
# db.session.add(c199)
# db.session.add(c200)
# db.session.add(c201)
# db.session.add(c202)
# db.session.add(c203)
# db.session.add(c204)
# db.session.add(c205)
# db.session.add(c206)
# db.session.add(c207)
# db.session.add(c208)
# db.session.add(c209)
# db.session.add(c210)
# db.session.add(c211)
# db.session.add(c212)
# db.session.add(c213)
# db.session.add(c214)
# db.session.add(c215)
# db.session.add(c216)
# db.session.add(c217)
# db.session.add(c218)
# db.session.add(c219)
# db.session.add(c220)
# db.session.add(c221)
# db.session.add(c222)
# db.session.add(c223)
# db.session.add(c224)
# db.session.add(c225)
# db.session.add(c226)
# db.session.add(c227)
# db.session.add(c228)
# db.session.add(c229)
# db.session.add(c230)
# db.session.add(c231)
# db.session.add(c232)
# db.session.add(c233)
# db.session.add(c234)
# db.session.add(c235)
# db.session.add(c236)
# db.session.add(c237)
# db.session.add(c238)
# db.session.add(c239)
# db.session.add(c240)
# db.session.add(c241)
# db.session.add(c242)
# db.session.add(c243)
# db.session.add(c244)
# db.session.add(c245)
# db.session.add(c246)
# db.session.add(c247)
# db.session.add(c248)
# db.session.add(c249)
# db.session.add(c250)
# db.session.add(c251)
# db.session.add(c252)

# db.session.commit()


# u1 = User.signup(
#     first_name='User',
#     last_name='One',
#     username='testuser1',
#     email='testuser1@testuser.com',
#     target_language='en',
#     city='New York',
#     country_iso='US',
#     password='password'
# )
# db.session.commit()

# u2 = User.signup(
#     first_name='User',
#     last_name='Two',
#     username='testuser2',
#     email='testuser2@testuser.com',
#     target_language='en',
#     city='Los Angeles',
#     country_iso='US',
#     password='password'
# )
# db.session.commit()

# u3 = User.signup(
#     first_name='user',
#     last_name='tHREE',
#     username='testuser3',
#     email='testuser3@testuser.com',
#     target_language='ja',
#     city='Tokyo',
#     country_iso='JP',
#     password='password'
# )
# db.session.commit()

# u4 = User.signup(
#     first_name='user',
#     last_name='Four',
#     username='testuser4',
#     email='testuser4@testuser.com',
#     target_language='es',
#     city='San Juan',
#     country_iso='PR',
#     password='password'
# )
# db.session.commit()


# t1 = Thread(
#     name=u1.username
# )
# t1.users.append(u1)
# t1.users.append(u2)
# db.session.add(t1)
# db.session.commit()


# l1 = Language(code='af', name='Afrikaans')
# l2 = Language(code='sq', name='Albanian')
# l3 = Language(code='am', name='Amharic')
# l4 = Language(code='ar', name='Arabic')
# l5 = Language(code='hy', name='Armenian')
# l6 = Language(code='as', name='Assamese')
# l7 = Language(code='ay', name='Aymara')
# l8 = Language(code='az', name='Azerbaijani')
# l9 = Language(code='bm', name='Bambara')
# l10 = Language(code='eu', name='Basque')
# l11 = Language(code='be', name='Belarusian')
# l12 = Language(code='bn', name='Bengali')
# l13 = Language(code='bho', name='Bhojpuri')
# l14 = Language(code='bs', name='Bosnian')
# l15 = Language(code='bg', name='Bulgarian')
# l16 = Language(code='ca', name='Catalan')
# l17 = Language(code='ceb', name='Cebuano')
# l18 = Language(code='zh-CN', name='Chinese (Simplified)')
# l19 = Language(code='zh', name='Chinese (Simplified)')
# l20 = Language(code='zh-TW', name='Chinese (Traditional)')
# l21 = Language(code='co', name='Corsican')
# l22 = Language(code='hr', name='Croatian')
# l23 = Language(code='cs', name='Czech')
# l24 = Language(code='da', name='Danish')
# l25 = Language(code='dv', name='Dhivehi')
# l26 = Language(code='doi', name='Dogri')
# l27 = Language(code='nl', name='Dutch')
# l28 = Language(code='en', name='English')
# l29 = Language(code='eo', name='Esperanto')
# l30 = Language(code='et', name='Estonian')
# l31 = Language(code='ee', name='Ewe')
# l32 = Language(code='fil', name='Filipino (Tagalog)')
# l33 = Language(code='fi', name='Finnish')
# l34 = Language(code='fr', name='French')
# l35 = Language(code='fy', name='Frisian')
# l36 = Language(code='gl', name='Galician')
# l37 = Language(code='ka', name='Georgian')
# l38 = Language(code='de', name='German')
# l39 = Language(code='el', name='Greek')
# l40 = Language(code='gn', name='Guarani')
# l41 = Language(code='gu', name='Gujarati')
# l42 = Language(code='ht', name='Haitian Creole')
# l43 = Language(code='ha', name='Hausa')
# l44 = Language(code='haw', name='Hawaiian')
# l45 = Language(code='he', name='Hebrew')
# l46 = Language(code='iw', name='Hebrew')
# l47 = Language(code='hi', name='Hindi')
# l48 = Language(code='hmn', name='Hmong')
# l49 = Language(code='hu', name='Hungarian')
# l50 = Language(code='is', name='Icelandic')
# l51 = Language(code='ig', name='Igbo')
# l52 = Language(code='ilo', name='Ilocano')
# l53 = Language(code='id', name='Indonesian')
# l54 = Language(code='ga', name='Irish')
# l55 = Language(code='it', name='Italian')
# l56 = Language(code='ja', name='Japanese')
# l57 = Language(code='jv', name='Javanese')
# l58 = Language(code='jw', name='Javanese')
# l59 = Language(code='kn', name='Kannada')
# l60 = Language(code='kk', name='Kazakh')
# l61 = Language(code='km', name='Khmer')
# l62 = Language(code='rw', name='Kinyarwanda')
# l63 = Language(code='gom', name='Konkani')
# l64 = Language(code='ko', name='Korean')
# l65 = Language(code='kri', name='Krio')
# l66 = Language(code='ku', name='Kurdish')
# l67 = Language(code='ckb', name='Kurdish (Sorani)')
# l68 = Language(code='ky', name='Kyrgyz')
# l69 = Language(code='lo', name='Lao')
# l70 = Language(code='la', name='Latin')
# l71 = Language(code='lv', name='Latvian')
# l72 = Language(code='ln', name='Lingala')
# l73 = Language(code='lt', name='Lithuanian')
# l74 = Language(code='lg', name='Luganda')
# l75 = Language(code='lb', name='Luxembourgish')
# l76 = Language(code='mk', name='Macedonian')
# l77 = Language(code='mai', name='Maithili')
# l78 = Language(code='mg', name='Malagasy')
# l79 = Language(code='ms', name='Malay')
# l80 = Language(code='ml', name='Malayalam')
# l81 = Language(code='mt', name='Maltese')
# l82 = Language(code='mi', name='Maori')
# l83 = Language(code='mr', name='Marathi')
# l84 = Language(code='mni-Mtei', name='Meiteilon (Manipuri)')
# l85 = Language(code='lus', name='Mizo')
# l86 = Language(code='mn', name='Mongolian')
# l87 = Language(code='my', name='Myanmar (Burmese)')
# l88 = Language(code='ne', name='Nepali')
# l89 = Language(code='no', name='Norwegian')
# l90 = Language(code='ny', name='Nyanja (Chichewa)')
# l91 = Language(code='or', name='Odia (Oriya)')
# l92 = Language(code='om', name='Oromo')
# l93 = Language(code='ps', name='Pashto')
# l94 = Language(code='fa', name='Persian')
# l95 = Language(code='pl', name='Polish')
# l96 = Language(code='pt', name='Portuguese (Portugal, Brazil)')
# l97 = Language(code='pa', name='Punjabi')
# l98 = Language(code='qu', name='Quechua')
# l99 = Language(code='ro', name='Romanian')
# l100 = Language(code='ru', name='Russian')
# l101 = Language(code='sm', name='Samoan')
# l102 = Language(code='sa', name='Sanskrit')
# l103 = Language(code='gd', name='Scots Gaelic')
# l104 = Language(code='nso', name='Sepedi')
# l105 = Language(code='sr', name='Serbian')
# l106 = Language(code='st', name='Sesotho')
# l107 = Language(code='sn', name='Shona')
# l108 = Language(code='sd', name='Sindhi')
# l109 = Language(code='si', name='Sinhala (Sinhalese)')
# l110 = Language(code='sk', name='Slovak')
# l111 = Language(code='sl', name='Slovenian')
# l112 = Language(code='so', name='Somali')
# l113 = Language(code='es', name='Spanish')
# l114 = Language(code='su', name='Sundanese')
# l115 = Language(code='sw', name='Swahili')
# l116 = Language(code='sv', name='Swedish')
# l117 = Language(code='tl', name='Tagalog (Filipino)')
# l118 = Language(code='tg', name='Tajik')
# l119 = Language(code='ta', name='Tamil')
# l120 = Language(code='tt', name='Tatar')
# l121 = Language(code='te', name='Telugu')
# l122 = Language(code='th', name='Thai')
# l123 = Language(code='ti', name='Tigrinya')
# l124 = Language(code='ts', name='Tsonga')
# l125 = Language(code='tr', name='Turkish')
# l126 = Language(code='tk', name='Turkmen')
# l127 = Language(code='ak', name='Twi (Akan)')
# l128 = Language(code='uk', name='Ukrainian')
# l129 = Language(code='ur', name='Urdu')
# l130 = Language(code='ug', name='Uyghur')
# l131 = Language(code='uz', name='Uzbek')
# l132 = Language(code='vi', name='Vietnamese')
# l133 = Language(code='cy', name='Welsh')
# l134 = Language(code='xh', name='Xhosa')
# l135 = Language(code='yi', name='Yiddish')
# l136 = Language(code='yo', name='Yoruba')
# l137 = Language(code='zu', name='Zulu')


# l1 = Language(code='AF', name='Afrikanns')
# l2 = Language(code='SQ', name='Albanian')
# l3 = Language(code='AR', name='Arabic')
# l4 = Language(code='HY', name='Armenian')
# l5 = Language(code='EU', name='Basque')
# l6 = Language(code='BN', name='Bengali')
# l7 = Language(code='BG', name='Bulgarian')
# l8 = Language(code='CA', name='Catalan')
# l9 = Language(code='KM', name='Cambodian')
# l10 = Language(code='ZH', name='Chinese (Mandarin)')
# l11 = Language(code='HR', name='Croation')
# l12 = Language(code='CS', name='Czech')
# l13 = Language(code='DA', name='Danish')
# l14 = Language(code='NL', name='Dutch')
# l15 = Language(code='EN', name='English')
# l16 = Language(code='ET', name='Estonian')
# l17 = Language(code='FJ', name='Fiji')
# l18 = Language(code='FI', name='Finnish')
# l19 = Language(code='FR', name='French')
# l20 = Language(code='KA', name='Georgian')
# l21 = Language(code='DE', name='German')
# l22 = Language(code='EL', name='Greek')
# l23 = Language(code='GU', name='Gujarati')
# l24 = Language(code='HE', name='Hebrew')
# l25 = Language(code='HI', name='Hindi')
# l26 = Language(code='HU', name='Hungarian')
# l27 = Language(code='IS', name='Icelandic')
# l28 = Language(code='ID', name='Indonesian')
# l29 = Language(code='GA', name='Irish')
# l30 = Language(code='IT', name='Italian')
# l31 = Language(code='JA', name='Japanese')
# l32 = Language(code='JW', name='Javanese')
# l33 = Language(code='KO', name='Korean')
# l34 = Language(code='LA', name='Latin')
# l35 = Language(code='LV', name='Latvian')
# l36 = Language(code='LT', name='Lithuanian')
# l37 = Language(code='MK', name='Macedonian')
# l38 = Language(code='MS', name='Malay')
# l39 = Language(code='ML', name='Malayalam')
# l40 = Language(code='MT', name='Maltese')
# l41 = Language(code='MI', name='Maori')
# l42 = Language(code='MR', name='Marathi')
# l43 = Language(code='MN', name='Mongolian')
# l44 = Language(code='NE', name='Nepali')
# l45 = Language(code='NO', name='Norwegian')
# l46 = Language(code='FA', name='Persian')
# l47 = Language(code='PL', name='Polish')
# l48 = Language(code='PT', name='Portuguese')
# l49 = Language(code='PA', name='Punjabi')
# l50 = Language(code='QU', name='Quechua')
# l51 = Language(code='RO', name='Romanian')
# l52 = Language(code='RU', name='Russian')
# l53 = Language(code='SM', name='Samoan')
# l54 = Language(code='SR', name='Serbian')
# l55 = Language(code='SK', name='Slovak')
# l56 = Language(code='SL', name='Slovenian')
# l57 = Language(code='ES', name='Spanish')
# l58 = Language(code='SW', name='Swahili')
# l59 = Language(code='SV', name='Swedish ')
# l60 = Language(code='TA', name='Tamil')
# l61 = Language(code='TT', name='Tatar')
# l62 = Language(code='TE', name='Telugu')
# l63 = Language(code='TH', name='Thai')
# l64 = Language(code='BO', name='Tibetan')
# l65 = Language(code='TO', name='Tonga')
# l66 = Language(code='TR', name='Turkish')
# l67 = Language(code='UK', name='Ukranian')
# l68 = Language(code='UR', name='Urdu')
# l69 = Language(code='UZ', name='Uzbek')
# l70 = Language(code='VI', name='Vietnamese')
# l71 = Language(code='CY', name='Welsh')
# l72 = Language(code='XH', name='Xhosa')


# db.session.add(l1)
# db.session.add(l2)
# db.session.add(l3)
# db.session.add(l4)
# db.session.add(l5)
# db.session.add(l6)
# db.session.add(l7)
# db.session.add(l8)
# db.session.add(l9)
# db.session.add(l10)
# db.session.add(l11)
# db.session.add(l12)
# db.session.add(l13)
# db.session.add(l14)
# db.session.add(l15)
# db.session.add(l16)
# db.session.add(l17)
# db.session.add(l18)
# db.session.add(l19)
# db.session.add(l20)
# db.session.add(l21)
# db.session.add(l22)
# db.session.add(l23)
# db.session.add(l24)
# db.session.add(l25)
# db.session.add(l26)
# db.session.add(l27)
# db.session.add(l28)
# db.session.add(l29)
# db.session.add(l30)
# db.session.add(l31)
# db.session.add(l32)
# db.session.add(l33)
# db.session.add(l34)
# db.session.add(l35)


# db.session.commit()


# u1.languages.append(l28)
# u2.languages.append(l28)
# u2.languages.append(l19)
# u2.languages.append(l56)
# u3.languages.append(l28)
# u3.languages.append(l56)
# u3.languages.append(l53)
# u4.languages.append(l28)
# u4.languages.append(l113)


# db.session.commit()
